### ISSUE TITLE
Class Troco - Troco (Construtor - Loop while - Contagem de notas de 2)

### ISSUE THREAD

**Issue by gelucasAmaral** [dbodanilo/Source-Code-Inspection#12]
Contagem de papeis moeda:

Na classe Troco, no loop while que realiza a contagem de notas de 2, a condição para entra no loop é usada de forma errônea, resultando na contagem incorreta de notas para o cálculo do troco.

Troco.java - Linhas 41 a 45

**Comment by dbodanilo** [comment]
merged pull request #27
