### ISSUE TITLE
Class Troco - Troco (Construtor - Loop while - Contagem de notas de 5)

### ISSUE THREAD

**Issue by gelucasAmaral** [dbodanilo/Source-Code-Inspection#15]
Contagem de papeis moeda:

Na classe Troco, no loop while que realizam as contagens dos papeis moeda, a condição para entra no loop é usada de forma errônea, resultando na contagem incorreta de notas de 5 para o cálculo do troco.

Troco.java - Linhas 36 a 38

**Comment by dbodanilo** [comment]
merged pull request #25
